SELECT 
    D.NAME AS DEPARTMENT_NAME, 
    COUNT(E.ID) AS COUNT_OF_EMPLOYEES_IN_THE_DEPARTMENT
FROM 
    DEPARTMENT D
LEFT JOIN 
    EMPLOYEE E 
ON 
    D.ID = E.DEPT_ID
GROUP BY 
    D.NAME
ORDER BY 
    COUNT_OF_EMPLOYEES_IN_THE_DEPARTMENT DESC, 
    DEPARTMENT_NAME ASC;
